### PR TITLE
Adding support for global preferences

### PR DESCRIPTION
**Pull request by Lichtjaeger**
I have added user global preferences for linting options.

### CODE REVIEW

**Comment by cfjedimaster** [comment]
Thank you!

**Comment by StephenESC** [comment]
How might I access those global preferences?
Thanks.

**Comment by cfjedimaster** [comment]
See the readme.md, it was updated to describe how.

**Comment by StephenESC** [comment]
I checked out the ReadMe file, thank you, but it doesn't provide any specifics on how to do it. Could you give me an example of what I would enter if I wanted the linter to ignore “box-sizing”?

Thanks.

**Comment by Lichtjaeger** [comment]
This is an example from my own brackets.json:

```
    ...
    "csslint.options": {
        "box-sizing": false,
        "box-model": false,
        "order-alphabetical": false,
        ...
    },
    "jshint.options": {
        "undef": true,
        "curly": true,
        ...
    }
}
```

**Comment by StephenESC** [comment]
Beautiful! Thank you, that’s exactly what I needed.
I’d never worked with a .json file before, so I was trying to piece together what it should’ve been based on examples above and other web pages. I was sooo close but never got it quite right.

One last question… will these preferences stay put next time I update Brackets or will they have to be reset every time there’s an update?

Thanks again to you both!

**Comment by Lichtjaeger** [comment]
They are definitely save for extension updates.
I'm not sure of Brackets-updates. But I think they keep the bower.json unaffected.

**Comment by cfjedimaster** [comment]
I'd be a bit worried since Preferences is still being nailed down in the
Brackets core (imo anyway). I'm sure they wouldn't blow them away willy
nilly, but until Preferences has a full UI in the editor, I'd consider it a
'beta' feature and be a bit concerned. Then again, it would take all of two
seconds to copy the file to a backup location too. ;)

On Thu, May 28, 2015 at 7:25 AM, Peter Scheler <notifications@github.com>
wrote:

> They are definitely save for extension updates.
> I'm not sure of Brackets-updates. But I think they keep the bower.json
> unaffected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-csslint/pull/40#issuecomment-106294918>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by StephenESC** [comment]
Making a backup copy right now. :)
Thank you, gentlemen!

**Comment by Bromooo** [comment]
@Lichtjaeger i still don’t get how to open the preference file... I have the latest csslint plugin on atom and I want to activate the alphabetical order warning ... I find that helpful 

Please can you show me the step by step process for me to achieve that PLEASE!!!🥺...

**Comment by Bromooo** [comment]
@Lichtjaeger kindly revert ASAP

**Comment by Lichtjaeger** [comment]
@Bromooo 
I haven't seen this for years and didn't even know that brackets is still in use or development. I use VSCode at the moment.

> @Lichtjaeger i still don’t get how to open the preference file... I have the latest csslint plugin on **atom** and I want to activate the alphabetical order warning ... I find that helpful

Are you sure, that you didn't bark up the wrong tree? This plugin is for the brackets editor. Not the atom editor.
Or do you only compare it with the plugin for atom?

> @Lichtjaeger kindly revert ASAP

Nope, you are the only one complaining about this in 5 years. @cfjedimaster is the owner of this repo and the plugin. Maybe he can do something for you or he might ask me to work on this.

**Comment by Bromooo** [comment]
> Are you sure, that you didn't bark up the wrong tree? This plugin is for the brackets editor. Not the atom editor.

Ohhh I thought it was for the atom editor 
I’m really sorry 


> Nope, you are the only one complaining about this in 5 years. @cfjedimaster is the owner of this repo and the plugin. Maybe he can do something for you or he might ask me to work on this.

Haha lol 

Thank you very much BTW

**Comment by cfjedimaster** [comment]
I don't use Brackets at all anymore - sorry. :)

**Pull request merged**
